export const genreMap: Record<number, string> = {
  3: "Acción",
  29: "Aventura",
  18: "Comedia",
  1: "Drama",
  42: "Recuentos de la vida",
  2: "Romance",
  5: "Venganza",
  6: "Harem",
  23: "Fantasía",
  31: "Sobrenatural",
  25: "Tragedia",
  43: "Psicológico",
  32: "Horror",
  44: "Thriller",
  28: "Historias cortas",
  30: "Ecchi",
  34: "Gore",
  27: "Girls love",
  45: "Boys love",
  41: "Reencarnación",
  37: "Sistema",
  33: "Ciencia ficción",
  38: "Apocalíptico",
  39: "Artes marciales",
  40: "Superpoderes",
  35: "Cultivación",
  8: "Milf",
};