// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetManhwaDetails(arg1) {
  return window['go']['main']['App']['GetManhwaDetails'](arg1);
}

export function GetManhwaHome() {
  return window['go']['main']['App']['GetManhwaHome']();
}

export function GetManhwaView(arg1) {
  return window['go']['main']['App']['GetManhwaView'](arg1);
}

export function GetSearchResults(arg1, arg2) {
  return window['go']['main']['App']['GetSearchResults'](arg1, arg2);
}
