// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetManhwaDetails(arg1:string):Promise<models.ManhwaDetails>;

export function GetManhwaHome():Promise<models.Home>;

export function GetManhwaView(arg1:string):Promise<models.ManhwaView>;

export function GetSearchResults(arg1:string,arg2:number):Promise<models.SearchData>;
